on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish packages to npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js 18.14.2
        uses: actions/setup-node@v3
        with:
          node-version: 18.14.2
          cache: "pnpm"
        env:
          NPM_TOKEN: ${{ secrets.PUBLISH_TOKEN }}

      - name: Install dependencies
        run: pnpm install

      - name: Publish all packages
        run: |
          pnpm -r build
          pnpm -r publish --tag latest --access public
        env:
          NPM_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
